---
apiVersion: v1
kind: Namespace
metadata:
  name: slim-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-slim-app
  namespace: slim-ns
  labels:
    app.kubernetes.io/name: nginx-slim-app
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx-slim: localhost/nginx-apparmor-profile
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: nginx-seccomp.json
  containers:
    - name: nginx-slim
      image: ghcr.io/vincepower/nginx-docker-slim:latest
      securityContext:
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 80
          name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-slim-svc
  namespace: slim-ns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-slim-app
  ports:
    - port: 80
      nodePort: 30003
      targetPort: 80
